import React from 'react';

interface AboutScreenProps {
  onBack: () => void;
  theme?: 'light' | 'dark';
}

export const AboutScreen: React.FC<AboutScreenProps> = ({ onBack, theme = 'light' }) => {
  const isDark = theme === 'dark';

  const sections = [
    {
      title: "What is Maargdarshan?",
      body: "Maargdarshan is a personal reflection and guidance application inspired by the Bhagavad Gita. It helps you explore real-life situations and emotions through verified teachings from the Gita, offering interpretation, reflection, and practical perspective."
    },
    {
      title: "Scripture integrity",
      body: "Every Gita verse displayed in Maargdarshan is sourced from verified, published translations and clearly attributed. The application never invents verses, chapter numbers, or Sanskrit text. AI explanations are always clearly distinguished from original scripture."
    },
    {
      title: "AI explanations",
      body: "The explanations, personal applications, and reflection questions generated by Maargdarshan are AI-assisted interpretations. They are presented as interpretive guidance, not as direct quotes from the Gita. The teaching itself always shows its source."
    },
    {
      title: "Content sources",
      body: "Verse translations are attributed to Swami Prabhupada's Bhagavad Gita As It Is, one of the most widely distributed English translations. Other translations may be added in future versions."
    },
    {
      title: "Not a replacement for care",
      body: "Maargdarshan is a tool for reflection and perspective. It is not a substitute for professional mental health care, counseling, or medical advice. If you are experiencing a crisis, please reach out to a qualified professional."
    }
  ];

  return (
    <div style={{
      background: isDark ? '#121614' : '#FAF7F2',
      color: isDark ? '#F3F0EA' : '#1C1917',
      minHeight: '100%',
      display: 'flex',
      flexDirection: 'column',
      transition: 'background 0.2s ease, color 0.2s ease'
    }}>
      {/* Sticky Header: < Back | About */}
      <div style={{
        position: 'sticky',
        top: 0,
        zIndex: 20,
        background: isDark ? 'rgba(18, 22, 20, 0.95)' : 'rgba(250, 247, 242, 0.95)',
        backdropFilter: 'blur(10px)',
        borderBottom: `1px solid ${isDark ? '#27342C' : '#ECE6DD'}`,
        padding: '16px 18px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between'
      }}>
        <button
          onClick={onBack}
          style={{
            background: 'none',
            border: 'none',
            cursor: 'pointer',
            color: isDark ? '#4ADE80' : '#1E5E3A',
            display: 'flex',
            alignItems: 'center',
            gap: 4,
            fontSize: 14.5,
            fontWeight: 600,
            padding: '4px 0'
          }}
          aria-label="Back to Settings"
        >
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
            <polyline points="15 18 9 12 15 6" />
          </svg>
          <span>Back</span>
        </button>

        <h1 style={{
          fontFamily: 'var(--font-display)',
          fontSize: 19,
          fontWeight: 600,
          color: isDark ? '#F3F0EA' : '#1C1917',
          margin: 0
        }}>
          About
        </h1>

        <div style={{ width: 48 }} />
      </div>

      {/* Scrollable Content Body */}
      <div style={{
        padding: '24px 20px 48px',
        display: 'flex',
        flexDirection: 'column',
        gap: 22
      }}>
        {/* Top Logo & App Title Section */}
        <div style={{
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          textAlign: 'center',
          paddingBottom: 22,
          borderBottom: `1px solid ${isDark ? '#27342C' : '#ECE6DD'}`
        }}>
          <div style={{
            width: 76,
            height: 76,
            marginBottom: 12,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            filter: 'drop-shadow(0 4px 12px rgba(0, 0, 0, 0.08))'
          }}>
            <img
              src="/peacock_feather.png"
              alt="Maargdarshan Logo"
              style={{
                width: '100%',
                height: '100%',
                objectFit: 'contain'
              }}
            />
          </div>

          {/* Hindi Devanagari Title */}
          <h2 style={{
            fontSize: 24,
            fontWeight: 700,
            color: isDark ? '#4ADE80' : '#1E5E3A',
            margin: '0 0 8px 0',
            letterSpacing: '0.02em'
          }}>
            मार्गदर्शन
          </h2>

          {/* Version Info */}
          <div style={{
            fontSize: 13,
            color: isDark ? '#9E988E' : '#6F6B64',
            marginBottom: 6,
            fontWeight: 500
          }}>
            Maargdarshan · Version 1.0.0
          </div>

          {/* English Tagline */}
          <p style={{
            fontSize: 13.5,
            color: isDark ? '#A6A095' : '#6F6B64',
            margin: 0,
            lineHeight: 1.45,
            maxWidth: 260
          }}>
            Find perspective through the wisdom of the Gita.
          </p>
        </div>

        {/* Content Paragraphs */}
        {sections.map((sec, idx) => (
          <div
            key={sec.title}
            style={{
              paddingBottom: idx === sections.length - 1 ? 0 : 20,
              borderBottom: idx === sections.length - 1 ? 'none' : `1px solid ${isDark ? '#27342C' : '#ECE6DD'}`
            }}
          >
            <h3 style={{
              fontSize: 15,
              fontWeight: 700,
              color: isDark ? '#F3F0EA' : '#1C1917',
              margin: '0 0 8px 0',
              lineHeight: 1.35
            }}>
              {sec.title}
            </h3>

            <p style={{
              fontSize: 13.5,
              color: isDark ? '#A6A095' : '#57534E',
              lineHeight: 1.6,
              margin: 0
            }}>
              {sec.body}
            </p>
          </div>
        ))}

        {/* Footer Credit */}
        <div style={{
          textAlign: 'center',
          paddingTop: 16,
          color: isDark ? '#78716C' : '#9C978F',
          fontSize: 12,
          fontWeight: 400
        }}>
          Made with care · 2026
        </div>
      </div>
    </div>
  );
};
